### ISSUE TITLE
Côte d'Ivoire not recognized with circumflex

### ISSUE THREAD

**Issue by Smylers** [openregister/picker-prototypes#26]
Ivory Coast is also known by its French name of [Côte d'Ivoire](https://www.wikiwand.com/en/Ivory_Coast), but your picker doesn't recognize it, not matching anything after ‘Cô’:
![Screen shot showing ‘no results found’ after typing ‘Cô’](https://user-images.githubusercontent.com/598534/40413983-134d81d4-5e6f-11e8-9ada-2718c0767d15.png)
It does work if you Asciify it as ‘Cote’ rather than ‘Côte’, but if somebody's going to use the French name they may expect it to have the French accent on it.

You could either add ‘Côte d'Ivoire’, and its longer form ‘The Republic of Côte d'Ivoire’, as additional endonyms. Or fix this more generally by ignoring all diacritics when matching.

**Comment by edwardhorsford** [comment]
Thanks for raising this @Smylers!

This repo is actually for an old prototype, rather than the real location picker. That can be found [here](https://github.com/alphagov/govuk-country-and-territory-autocomplete).

I've added a description to the repo to make that more clear.

I'll respond more fully in the other repo.
